# expects: cygwin|Windows
# call: winpty docker-compose.exe run --rm app pdfimages -all ./pdf/1.pdf ./pdf/1
#

version: "3.4"

services:
  app:
    build: .
    volumes:
      # Windows only
      - c:\Users:/home
    network_mode: bridge
    working_dir: /home/$USER/Documents
